AObuchow/lsp4xml-extensions-maven

org.eclipse.lsp4xml.extensions.maven/pom.xml
Initiate a specific versioning for the project as we're not sure it evolves and releases in sync with LSP4XML.
Also uses SNAPSHOT as we're not supposed to changed content for released version.
=> Use own snapshot version

org.eclipse.lsp4xml.extensions.maven/pom.xml
=> Fix version for dependency

LICENSE.md, org.eclipse.lsp4xml.extensions.maven/pom.xml, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/commons/snippets/Snippet.java, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/commons/snippets/SnippetContext.java, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/commons/snippets/SnippetRegistry.java, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/DependencyScope.java, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/DiagnosticRequest.java, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/MavenCompletionParticipant.java, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/MavenDiagnosticParticipant.java, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/SubModuleValidator.java, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/VersionValidator.java, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/searcher/ArtifactSearcherManager.java, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/searcher/IArtifactSearcher.java, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/searcher/LocalArtifactSearcher.java, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/searcher/LocalSubModuleSearcher.java, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/searcher/ParentSearcher.java
=> License + Copyright headers

org.eclipse.lsp4xml.extensions.maven/pom.xml, org.eclipse.lsp4xml.extensions.maven/src/test/java/org/eclipse/lsp4xml/extensions/maven/test/ClientServerConnection.java, org.eclipse.lsp4xml.extensions.maven/src/test/java/org/eclipse/lsp4xml/extensions/maven/test/ExtensionTests.java, org.eclipse.lsp4xml.extensions.maven/src/test/resources/pom-with-module-error.xml
=> Add first test cases

org.eclipse.lsp4xml.extensions.maven/pom.xml, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/MavenDiagnosticParticipant.java, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/MavenPlugin.java, org.eclipse.lsp4xml.extensions.maven/src/test/java/org/eclipse/lsp4xml/extensions/maven/test/ExtensionTests.java, org.eclipse.lsp4xml.extensions.maven/src/test/resources/pom-without-artifactId.xml
=> Report problems from ProjectBuilder as diagnostics

org.eclipse.lsp4xml.extensions.maven/.gitignore, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/VersionValidator.java
Fix error on missing artifactId/groupId/version + add workingCopy files
to .gitignore
=> Fix version validator artifact initilization errors

org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/MavenCompletionParticipant.java, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/MavenProjectCache.java, org.eclipse.lsp4xml.extensions.maven/src/test/java/org/eclipse/lsp4xml/extensions/maven/test/ExtensionTest.java
=> Fixes and refactoring to property completion

org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/MavenProjectCache.java, org.eclipse.lsp4xml.extensions.maven/src/test/java/org/eclipse/lsp4xml/extensions/maven/test/ExtensionTest.java
=> Read changed document instead of local file

org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/MavenCompletionParticipant.java, org.eclipse.lsp4xml.extensions.maven/src/test/java/org/eclipse/lsp4xml/extensions/maven/test/ExtensionTest.java
=> Support for "native" properties

org.eclipse.lsp4xml.extensions.maven/pom.xml
=> Version Bump

org.eclipse.lsp4xml.extensions.maven/src/test/java/org/eclipse/lsp4xml/extensions/maven/test/ExtensionTest.java, org.eclipse.lsp4xml.extensions.maven/src/test/resources/pom-with-properties-in-parent.xml
=> Add test for completion using parent properties

org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/MavenCompletionParticipant.java, org.eclipse.lsp4xml.extensions.maven/src/test/java/org/eclipse/lsp4xml/extensions/maven/test/ExtensionTest.java, org.eclipse.lsp4xml.extensions.maven/src/test/resources/pom-with-dependency.xml
=> Support for completion of <dependency>

org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/DiagnosticRequest.java, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/MavenCompletionParticipant.java, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/MavenDiagnosticParticipant.java, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/MavenPlugin.java, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/MavenProjectCache.java, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/SubModuleValidator.java, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/searcher/ParentSearcher.java
=> Format codebase

org.eclipse.lsp4xml.extensions.maven/pom.xml, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/MavenCompletionParticipant.java, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/MavenPlugin.java, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/VersionValidator.java, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/searcher/RemoteRepositoryIndexSearcher.java, org.eclipse.lsp4xml.extensions.maven/src/test/java/org/eclipse/lsp4xml/extensions/maven/test/ExtensionTest.java, org.eclipse.lsp4xml.extensions.maven/src/test/resources/pom-remote-artifactId-complete.xml, org.eclipse.lsp4xml.extensions.maven/src/test/resources/pom-remote-groupId-complete.xml, org.eclipse.lsp4xml.extensions.maven/src/test/resources/pom-remote-version-complete.xml
=> Add remote groupId, artifactId completion

org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/searcher/RemoteRepositoryIndexSearcher.java
=> Move location of maven indexes

org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/MavenCompletionParticipant.java, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/MavenProjectCache.java, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/searcher/RemoteRepositoryIndexSearcher.java, org.eclipse.lsp4xml.extensions.maven/src/test/java/org/eclipse/lsp4xml/extensions/maven/test/RemoteRepositoryTest.java, org.eclipse.lsp4xml.extensions.maven/src/test/resources/pom-remote-plugin-artifactId-complete.xml, org.eclipse.lsp4xml.extensions.maven/src/test/resources/pom-remote-plugin-groupId-complete.xml, org.eclipse.lsp4xml.extensions.maven/src/test/resources/pom-remote-plugin-version-complete.xml
add remote plugin GAV completion for #32
=> Add remote plugin GAV autocomplete, use model as fallback in projectbuildingerror

org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/MavenCompletionParticipant.java, org.eclipse.lsp4xml.extensions.maven/src/test/java/org/eclipse/lsp4xml/extensions/maven/test/PluginTest.java, org.eclipse.lsp4xml.extensions.maven/src/test/resources/pom-plugin-config-tag.xml
=> Improve configuration element completion

org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/MavenProjectCache.java
Use more flexible ModelSource2
=> Avoid creation of working copies

org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/DOMUtils.java, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/MavenCompletionParticipant.java, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/MavenHoverParticipant.java, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/MavenPlugin.java, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/MavenPluginUtils.java, org.eclipse.lsp4xml.extensions.maven/src/test/java/org/eclipse/lsp4xml/extensions/maven/test/PluginTest.java, org.eclipse.lsp4xml.extensions.maven/src/test/java/org/eclipse/lsp4xml/extensions/maven/test/RemoteRepositoryTest.java, org.eclipse.lsp4xml.extensions.maven/src/test/resources/pom-plugin-configuration-hover.xml, org.eclipse.lsp4xml.extensions.maven/src/test/resources/pom-plugin-goal-hover.xml
Signed-off-by: Andrew Obuchowicz aobuchow@redhat.com
=> Maven plugin configuration & goal hover + refactorings

org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/MavenCompletionParticipant.java, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/MavenParseUtils.java, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/VersionValidator.java, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/searcher/LocalRepositorySearcher.java, org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/searcher/RemoteRepositoryIndexSearcher.java, org.eclipse.lsp4xml.extensions.maven/src/test/java/org/eclipse/lsp4xml/extensions/maven/test/RemoteRepositoryTest.java, org.eclipse.lsp4xml.extensions.maven/src/test/java/org/eclipse/lsp4xml/extensions/maven/test/SimpleModelTest.java
* Some code improvements
* Make completion on artifactId only complete if groupId match
=> Improve some completion

org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/MavenPluginUtils.java
Fix #71
Signed-off-by: Andrew Obuchowicz aobuchow@redhat.com
=> Fix newlines in plugin configuration hover & completion description

org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/MavenPluginUtils.java
=> Use \n\n instead of <br/> for getMarkupDescription

org.eclipse.lsp4xml.extensions.maven/src/main/java/org/eclipse/lsp4xml/extensions/maven/MavenCompletionParticipant.java
=> Support insertion of <groupId> and <version> with <artifactId>

lemminx-maven/pom.xml
=> Bump version to 0.0.2-SNAPSHOT for m2e use

lemminx-maven/src/main/java/org/eclipse/lemminx/maven/MavenHoverParticipant.java, lemminx-maven/src/main/java/org/eclipse/lemminx/maven/searcher/RemoteRepositoryIndexSearcher.java, lemminx-maven/src/test/java/org/eclipse/lemminx/maven/test/ClientServerConnection.java, lemminx-maven/src/test/java/org/eclipse/lemminx/maven/test/LocalRepoTests.java, lemminx-maven/src/test/java/org/eclipse/lemminx/maven/test/PluginTest.java, lemminx-maven/src/test/java/org/eclipse/lemminx/maven/test/RemoteRepositoryTest.java, lemminx-maven/src/test/java/org/eclipse/lemminx/maven/test/SimpleModelTest.java, lemminx-maven/src/test/resources/pom-remote-artifact-hover.xml
=> Fix tests now that we're using LemMinX

lemminx-maven/src/test/java/org/eclipse/lemminx/maven/test/ClientServerConnection.java, lemminx-maven/src/test/java/org/eclipse/lemminx/maven/test/LocalRepoTests.java, lemminx-maven/src/test/java/org/eclipse/lemminx/maven/test/PluginTest.java, lemminx-maven/src/test/java/org/eclipse/lemminx/maven/test/RemoteRepositoryTest.java, lemminx-maven/src/test/java/org/eclipse/lemminx/maven/test/SimpleModelTest.java
=> Shutdown LS properly in tests
